---
- import_tasks: install_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: install_redhat.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int == 7
